version: '3.1'

services:
  mongodbserver:
    image: mongo
    restart: always
    # mem_limit: 8192m
#    logging:
#      options:
#        "max-size": 2048m
    stdin_open: true
    volumes:
      - ./data:/data/db
    tty: true
    ports:
      - 27017:27017/tcp
    environment:
      #      MONGO_INITDB_ROOT_USERNAME: root
      #      MONGO_INITDB_ROOT_PASSWORD: example
      wiredTigerCacheSizeGB: 3
    networks:
      - mongo_jupyter_integration



  # mongo-express:
  #     image: mongo-express
  #     restart: always
  #     ports:
  #       - 8081:8081
#      environment:
#        ME_CONFIG_MONGODB_ADMINUSERNAME: root
#        ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
    mongo_jupyter_integration:
        external: true
